model:
  name: "LogisticRegression"
  dim: 3072

dataset:
  path: "data"
  batch_size: 512
  shuffle: True
  num_workers: 32
  drop_last: False
  gray_scale: False
  hog_feature: False
  preprocess: False

optimizer:
  type: "AdamW"
  params:
    lr: 0.001
    weight_decay: 0.00

trainer:
  num_classes: 10
  max_epoch: 50
  extra: False

stats:
  stats_dir: "stats"
  stats_folder: "logistic_regression/RGB-512/"