model:
  name: "LogisticRegression"
  dim: 1024

dataset:
  path: "data"
  batch_size: 128
  shuffle: True
  num_workers: 32
  drop_last: False
  gray_scale: True
  hog_feature: False
  preprocess: False

optimizer:
  type: "AdamW"
  params:
    lr: 0.01
    weight_decay: 0.00

trainer:
  num_classes: 10
  max_epoch: 50
  extra: False

stats:
  stats_dir: "stats"
  stats_folder: "logistic_regression/categorical/gray-0.01/"