model:
  name: "LogisticRegression"
  dim: 8100
  num_classes: 10
  loss_type: "default"

dataset:
  path: "data"
  batch_size: 128
  shuffle: True
  num_workers: 32
  drop_last: False
  gray_scale: True
  hog_feature: True
  block_size: 2
  cell_size: 2
  bin_size: 9

optimizer:
  type: "AdamW"
  params:
    lr: 0.001

trainer:
  max_epoch: 20
  extra: False

stats:
  stats_dir: "stats"
  stats_folder: "logisitc_regression/HOG/"