model:
  name: "LogisticRegression"
  dim: 3072
  num_classes: 10
  loss_type: "default"

dataset:
  path: "data"
  batch_size: 128
  shuffle: True
  num_workers: 32
  drop_last: False
  gray_scale: False
  hog_feature: False

optimizer:
  type: "AdamW"
  params:
    lr: 0.001

trainer:
  max_epoch: 20
  extra: False

stats:
  stats_dir: "stats"
  stats_folder: "logisitc_regression/RGB/"